### ISSUE TITLE
Can't make works the skarf_trackThreejsScene.html example locally

### ISSUE THREAD

**Issue by ghost** [skeelogy/skarf.js#1]
Hello, first of all thanks for your answer in stackoverflow and for this skarf.js framework. 
I've cloned the git this morning and I canno't use the example locally althought it works viewing it from github.io.
I tried to run it on a XAmmp server on linux with mozilla or chrome and the console give me an error: `Error: mainMarkerId not specified @ https://localhost/skarf.js/skarf.min.js:32` It seems that the problem comes loading the json file which define this value, ie `models_jsartoolkit.json`.

**Comment by skeelogy** [comment]
Looks like somewhere in the execution, mainMarkerId is undefined. Not sure how that could happen.

Can I just double check that you are doing these things:
- running the server with the root in the `/path/to/skarf.js/` folder
- running the example using an url like `http://localhost:8080/examples/skarf_trackThreejsScene.html` (whichever port that your server is opened for)

The console should have these lines somewhere:

```
Loading markers json file: models/models_jsartoolkit.json
Loaded models/models_jsartoolkit.json
Main marker id: 22
Loading markers json file: models/models_jsaruco.json
Loaded models/models_jsaruco.json
Main marker id: 1001
Using tracking lib: JSARToolKit
```

If it still does not work, I might need the full console output from your web browser.

**Comment by ghost** [comment]
Thanks for your rapid answer,
I'm running my server locally as I do normally, cloning the repository in my root server directory. 
I tried to put the examples directory in the root directory of my local server, I even tried to put it on distant server and it do not works with the same error of `mainMarkerId not specified.`

Here's the link:http://benjamin.abel.free.fr/skarf.js/examples/myskarf_trackThreejsScene.html

And here's the console log from chrome

```
[blocked] The page at https://localhost/skarf.js/examples/myskarf_trackThreejsScene.html ran insecure content from http://fonts.googleapis.com/css?family=Fauna+One. myskarf_trackThreejsScene.html:7
Using SKARF 1.0.3 skarf.js:80
Document is ready. myskarf_trackThreejsScene.html:444
THREE.WebGLRenderer 58 three.min.js:408
THREE.WebGLRenderer 58 three.min.js:408
Loading markers json file: models/models_jsartoolkit.json skarf.js:1127
Loaded models/models_jsartoolkit.json skarf.js:1136
Main marker id: undefined skarf.js:1137

    Uncaught Error: mainMarkerId not specified skarf.js:1289

Content script: Base content script, started on url: https://localhost/skarf.js/examples/myskarf_trackThreejsScene.html base-content-script.js:298
```

I'm using here a modified version named `myskarf_trackThreejsScene.html`, the only difference is that it uses the `skarf.js` library and not the minfied one.

The errors are the same with the original html page:http://benjamin.abel.free.fr/skarf.js/examples/skarf_trackThreejsScene.html

**Comment by skeelogy** [comment]
Thanks for the online example from your server. I know what's going on now. Looks like the JSON file got loaded but did not return the right data type (string instead of JSON object). This doesn't happen when I use node.js' http-server module.

I've put in a fix that should solve this issue. Can you pull/fetch the latest codes and then try again?

**Comment by ghost** [comment]
Thanks you, it works perfectly even without a server running.

**Comment by skeelogy** [comment]
I would have thought there there will be some cross-origin errors if you do not use a server. Anyway, glad that it works for you now!

**Comment by ghost** [comment]
Thank you very much fo your help, and for this library. It's really a great
job.
