### ISSUE TITLE
marker source

### ISSUE THREAD

**Issue by satore11** [skeelogy/skarf.js#2]
Hi,
can i change the markers source? If yes, how?
Thanks

**Comment by skeelogy** [comment]
Hi satore11, I'm not sure what you mean by changing the markers source. Did you mean changing the visible encoding pattern of each number?

**Comment by satore11** [comment]
Hi, thanks for your answer.
example: if i want to track another draw like http://ignorethecode.net/blog_images/editormatch/10.jpg

**Comment by skeelogy** [comment]
Skarf.js uses either JSARToolKit or js-aruco, but neither of these libraries have demonstrated the use of custom markers.

It might be worth raising this question to their individual github repositories:
JSARToolKit: https://github.com/kig/JSARToolKit
js-aruco: https://github.com/jcmellado/js-aruco

If either of these libraries are able to detect custom markers, then it will be possible for skarf.js to handle them as well. But at the moment, I've only built and tested skarf.js against ID markers (i.e. markers that encode an ID, such as those that are included in this repository).
